// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjjnliztykbaewgughog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqam5saXp0eWtiYWV3Z3VnaG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDIwMDcsImV4cCI6MjA2NzkxODAwN30.edum5fiOrOL7kuduxlXfzfDXfOVjm5I0npr780r_ihI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});